# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/servlet

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout


      # Download and cache dependencies
      - restore_cache:
          keys:
            - vl-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - vl-dependencies-

      - run: mvn dependency:go-offline -f pom.xml
      - save_cache:
          paths:
            - ~/.m2
          key: vl-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test -f pom.xml
      - run: mvn test

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master



workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: master # only run deploy-via-git job on master branch